/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Payment;

import Connection.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.internal.org.objectweb.asm.tree.TryCatchBlockNode;

/**
 *
 * @author Sandaru Muthuwadige
 */
public class NewStudent extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    int id = 0;

    /**
     * Creates new form NewStudent
     */
    public NewStudent() {
        initComponents();
// Connect to Database
        con = DBconnect.connect();
        jButton4.setVisible(false);

    }
    
        NewStudent(int id) {
        this();
        this.id = id;
        jButton3.setVisible(false);
        jButton4.setVisible(true);
        try {
            Connection c = DBconnect.connect();
            Statement s;
            s = c.createStatement();
            ResultSet rs = s.executeQuery("select * from student where admission = '"+id+"'");
            if (rs.next()) {
                sadmission.setText(rs.getString("admission"));
                sname.setText(rs.getString("name"));
                sgrade.setText(rs.getString("grade"));
                smobile.setText(rs.getString("mobile"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        sgrade = new javax.swing.JTextField();
        sadmission = new javax.swing.JTextField();
        smobile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Student - Payment Manager");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nexa Bold", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add New Student");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 80, 200, 30);

        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        jPanel1.add(sname);
        sname.setBounds(200, 180, 450, 30);

        sgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgradeActionPerformed(evt);
            }
        });
        jPanel1.add(sgrade);
        sgrade.setBounds(200, 230, 450, 30);

        sadmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sadmissionActionPerformed(evt);
            }
        });
        jPanel1.add(sadmission);
        sadmission.setBounds(200, 130, 450, 30);

        smobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smobileActionPerformed(evt);
            }
        });
        jPanel1.add(smobile);
        smobile.setBounds(200, 280, 450, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Mobile No");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 280, 100, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Admission No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 130, 100, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Grade");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 230, 90, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 180, 90, 29);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Payment/Images/tick.png"))); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(210, 340, 130, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Payment/Images/tick.png"))); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(360, 340, 130, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Payment/Images/back.png"))); // NOI18N
        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(510, 340, 130, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Talent Show 2018\\PaymentSystem\\UI\\Base.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 700, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(705, 468));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void sgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgradeActionPerformed

    private void sadmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sadmissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sadmissionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       StudentDetails mframe = new StudentDetails();
       mframe.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
//---------------- Getting Data From Jframe ----------------//
            String admission    = sadmission.getText();
            String name         = sname.getText();
            String grade        = sgrade.getText();
            String mobile       = smobile.getText();
            String status       = "Not Paid";
//---------------- Getting Data Over ----------------//    
            
            String q = "Insert into student (admission,name,grade,mobile,status) values ('"+admission+"','"+name+"','"+grade+"','"+mobile+"','"+status+"')";
            pst = con.prepareStatement(q);
            pst.execute();
           
            JOptionPane.showMessageDialog(this, "Succeefully Saved!","Succefull", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Occured! Try again","Error",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
//---------------- Getting Data From Jframe ----------------//
            String admission    = sadmission.getText();
            String name         = sname.getText();
            String grade        = sgrade.getText();
            String mobile       = smobile.getText();
            //String status       = "Not Paid";
//---------------- Getting Data Over ----------------//   
            Connection c = DBconnect.connect();
            Statement s;
            s = c.createStatement();
            s.executeUpdate("Update student set admission = '"+admission+"', name = '"+name+"', grade = '"+grade+"', mobile = '"+mobile+"' where admission = '"+admission+"'");
            
            JOptionPane.showMessageDialog(this, "Succeefully Saved!","Succefull", JOptionPane.INFORMATION_MESSAGE);
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Occured! Try again","Error",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void smobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smobileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sadmission;
    private javax.swing.JTextField sgrade;
    private javax.swing.JTextField smobile;
    private javax.swing.JTextField sname;
    // End of variables declaration//GEN-END:variables
}
